# Generated by Django 3.2.5 on 2021-09-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='weather',
            field=models.CharField(blank=True, help_text='날씨API 연동하기 위한 정보', max_length=150, null=True),
        ),
    ]
