# Generated by Django 3.2.5 on 2021-09-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_site_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='weather',
            field=models.JSONField(blank=True, help_text='날씨API 연동하기 위한 위경도 정보', null=True),
        ),
    ]
