# Generated by Django 3.2.5 on 2021-09-07 03:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_alter_site_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='weather',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='날씨API 연동하기 위한 위경도 정보', null=True),
        ),
    ]
