# Generated by Django 3.2.5 on 2021-08-25 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='제목', max_length=150)),
                ('content', models.TextField(blank=True, help_text='내용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(help_text='캠핑장정보 FK', on_delete=django.db.models.deletion.CASCADE, to='camp.site')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Free_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('free', models.ForeignKey(help_text='자유게시판 FK', on_delete=django.db.models.deletion.CASCADE, to='board.free')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='제목', max_length=150)),
                ('content', models.TextField(blank=True, help_text='내용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(help_text='캠핑장정보 FK', on_delete=django.db.models.deletion.CASCADE, to='camp.site')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='제목', max_length=150)),
                ('photo', models.ImageField(default='default.jpeg', help_text='대표이미지', upload_to='')),
                ('content', models.TextField(blank=True, help_text='내용', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(help_text='캠핑장정보 FK', on_delete=django.db.models.deletion.CASCADE, to='camp.site')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(help_text='후기 FK', on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('post_comment', models.ForeignKey(help_text='후기 댓글 FK', on_delete=django.db.models.deletion.CASCADE, to='board.post_comment')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, help_text='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('post', models.ForeignKey(help_text='후기 FK', on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('post', models.ForeignKey(help_text='후기 FK', on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, help_text='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('notice', models.ForeignKey(help_text='공지사항 FK', on_delete=django.db.models.deletion.CASCADE, to='board.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Free_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('free_comment', models.ForeignKey(help_text='자유게시판 댓글 FK', on_delete=django.db.models.deletion.CASCADE, to='board.free_comment')),
                ('user', models.ForeignKey(help_text='작성자 FK', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Free_hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, help_text='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('free', models.ForeignKey(help_text='자유게시판 FK', on_delete=django.db.models.deletion.CASCADE, to='board.free')),
            ],
        ),
    ]
