# Generated by Django 3.2.5 on 2021-08-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.CharField(help_text='대표이미지', max_length=100, null=True),
        ),
    ]
