# Generated by Django 3.2.5 on 2021-09-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_reply',
            name='free_comment',
            field=models.ForeignKey(help_text='자유게시판 댓글 FK', on_delete=django.db.models.deletion.CASCADE, related_name='children_free_reply', to='board.free_comment'),
        ),
        migrations.AlterField(
            model_name='post_reply',
            name='post_comment',
            field=models.ForeignKey(help_text='후기 댓글 FK', on_delete=django.db.models.deletion.CASCADE, related_name='children_post_reply', to='board.post_comment'),
        ),
    ]
